[package]
name = "aoc_fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["cookies"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.17"
dotenv = "0.15"
